server:
  port: 5051
  #port: ${PORT:0}
spring:
  application:
    name: resell-users

eureka:
  instance:
    instance-id=${spring:application:name}:${spring:application:instance_id:${random:value}}
  client:
    service-url:
      defaultzone: http://localhost:8761




